(cl:defpackage real_test-srv
  (:use )
  (:export
   "ADDEYETOHANDSAMPLE"
   "<ADDEYETOHANDSAMPLE-REQUEST>"
   "ADDEYETOHANDSAMPLE-REQUEST"
   "<ADDEYETOHANDSAMPLE-RESPONSE>"
   "ADDEYETOHANDSAMPLE-RESPONSE"
  ))

