// Generated by gencpp from file real_test/AddEyeToHandSampleRequest.msg
// DO NOT EDIT!


#ifndef REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLEREQUEST_H
#define REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace real_test
{
template <class ContainerAllocator>
struct AddEyeToHandSampleRequest_
{
  typedef AddEyeToHandSampleRequest_<ContainerAllocator> Type;

  AddEyeToHandSampleRequest_()
    : base_x(0.0)
    , base_y(0.0)
    , base_z(0.0)
    , optical_x(0.0)
    , optical_y(0.0)
    , optical_z(0.0)  {
    }
  AddEyeToHandSampleRequest_(const ContainerAllocator& _alloc)
    : base_x(0.0)
    , base_y(0.0)
    , base_z(0.0)
    , optical_x(0.0)
    , optical_y(0.0)
    , optical_z(0.0)  {
  (void)_alloc;
    }



   typedef float _base_x_type;
  _base_x_type base_x;

   typedef float _base_y_type;
  _base_y_type base_y;

   typedef float _base_z_type;
  _base_z_type base_z;

   typedef float _optical_x_type;
  _optical_x_type optical_x;

   typedef float _optical_y_type;
  _optical_y_type optical_y;

   typedef float _optical_z_type;
  _optical_z_type optical_z;





  typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddEyeToHandSampleRequest_

typedef ::real_test::AddEyeToHandSampleRequest_<std::allocator<void> > AddEyeToHandSampleRequest;

typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleRequest > AddEyeToHandSampleRequestPtr;
typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleRequest const> AddEyeToHandSampleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator1> & lhs, const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.base_x == rhs.base_x &&
    lhs.base_y == rhs.base_y &&
    lhs.base_z == rhs.base_z &&
    lhs.optical_x == rhs.optical_x &&
    lhs.optical_y == rhs.optical_y &&
    lhs.optical_z == rhs.optical_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator1> & lhs, const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "855ed419012aa2e204e450eb6966a5a4";
  }

  static const char* value(const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x855ed419012aa2e2ULL;
  static const uint64_t static_value2 = 0x04e450eb6966a5a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_test/AddEyeToHandSampleRequest";
  }

  static const char* value(const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 手动增加一对 3D 对应点：同一点在基座系与相机光学系下的坐标（米）\n"
"float32 base_x\n"
"float32 base_y\n"
"float32 base_z\n"
"float32 optical_x\n"
"float32 optical_y\n"
"float32 optical_z\n"
;
  }

  static const char* value(const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_x);
      stream.next(m.base_y);
      stream.next(m.base_z);
      stream.next(m.optical_x);
      stream.next(m.optical_y);
      stream.next(m.optical_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddEyeToHandSampleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_test::AddEyeToHandSampleRequest_<ContainerAllocator>& v)
  {
    s << indent << "base_x: ";
    Printer<float>::stream(s, indent + "  ", v.base_x);
    s << indent << "base_y: ";
    Printer<float>::stream(s, indent + "  ", v.base_y);
    s << indent << "base_z: ";
    Printer<float>::stream(s, indent + "  ", v.base_z);
    s << indent << "optical_x: ";
    Printer<float>::stream(s, indent + "  ", v.optical_x);
    s << indent << "optical_y: ";
    Printer<float>::stream(s, indent + "  ", v.optical_y);
    s << indent << "optical_z: ";
    Printer<float>::stream(s, indent + "  ", v.optical_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLEREQUEST_H
