// Generated by gencpp from file real_test/AddEyeToHandSampleResponse.msg
// DO NOT EDIT!


#ifndef REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLERESPONSE_H
#define REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace real_test
{
template <class ContainerAllocator>
struct AddEyeToHandSampleResponse_
{
  typedef AddEyeToHandSampleResponse_<ContainerAllocator> Type;

  AddEyeToHandSampleResponse_()
    : success(false)
    , message()
    , count(0)  {
    }
  AddEyeToHandSampleResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , count(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddEyeToHandSampleResponse_

typedef ::real_test::AddEyeToHandSampleResponse_<std::allocator<void> > AddEyeToHandSampleResponse;

typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleResponse > AddEyeToHandSampleResponsePtr;
typedef boost::shared_ptr< ::real_test::AddEyeToHandSampleResponse const> AddEyeToHandSampleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator1> & lhs, const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator1> & lhs, const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c80d4d2084ba02c680df535380f6464";
  }

  static const char* value(const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c80d4d2084ba02cULL;
  static const uint64_t static_value2 = 0x680df535380f6464ULL;
};

template<class ContainerAllocator>
struct DataType< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_test/AddEyeToHandSampleResponse";
  }

  static const char* value(const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"int32 count\n"
"\n"
;
  }

  static const char* value(const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddEyeToHandSampleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_test::AddEyeToHandSampleResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLERESPONSE_H
