// Generated by gencpp from file real_test/AddEyeToHandSample.msg
// DO NOT EDIT!


#ifndef REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLE_H
#define REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLE_H

#include <ros/service_traits.h>


#include <real_test/AddEyeToHandSampleRequest.h>
#include <real_test/AddEyeToHandSampleResponse.h>


namespace real_test
{

struct AddEyeToHandSample
{

typedef AddEyeToHandSampleRequest Request;
typedef AddEyeToHandSampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddEyeToHandSample
} // namespace real_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::real_test::AddEyeToHandSample > {
  static const char* value()
  {
    return "b1d912318536383476f3a61d6d9c6b77";
  }

  static const char* value(const ::real_test::AddEyeToHandSample&) { return value(); }
};

template<>
struct DataType< ::real_test::AddEyeToHandSample > {
  static const char* value()
  {
    return "real_test/AddEyeToHandSample";
  }

  static const char* value(const ::real_test::AddEyeToHandSample&) { return value(); }
};


// service_traits::MD5Sum< ::real_test::AddEyeToHandSampleRequest> should match
// service_traits::MD5Sum< ::real_test::AddEyeToHandSample >
template<>
struct MD5Sum< ::real_test::AddEyeToHandSampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::real_test::AddEyeToHandSample >::value();
  }
  static const char* value(const ::real_test::AddEyeToHandSampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::real_test::AddEyeToHandSampleRequest> should match
// service_traits::DataType< ::real_test::AddEyeToHandSample >
template<>
struct DataType< ::real_test::AddEyeToHandSampleRequest>
{
  static const char* value()
  {
    return DataType< ::real_test::AddEyeToHandSample >::value();
  }
  static const char* value(const ::real_test::AddEyeToHandSampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::real_test::AddEyeToHandSampleResponse> should match
// service_traits::MD5Sum< ::real_test::AddEyeToHandSample >
template<>
struct MD5Sum< ::real_test::AddEyeToHandSampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::real_test::AddEyeToHandSample >::value();
  }
  static const char* value(const ::real_test::AddEyeToHandSampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::real_test::AddEyeToHandSampleResponse> should match
// service_traits::DataType< ::real_test::AddEyeToHandSample >
template<>
struct DataType< ::real_test::AddEyeToHandSampleResponse>
{
  static const char* value()
  {
    return DataType< ::real_test::AddEyeToHandSample >::value();
  }
  static const char* value(const ::real_test::AddEyeToHandSampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REAL_TEST_MESSAGE_ADDEYETOHANDSAMPLE_H
